version = 0.1

[default.deploy.parameters]
stack_name = "image-processor"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "image-processor"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
